import { DollarSign, Clock } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { useQuery } from "@tanstack/react-query";
import type { PayslipRecord } from "@shared/schema";
import { Skeleton } from "@/components/ui/skeleton";

export default function PayslipPage() {
  const { data: payslipsData, isLoading } = useQuery<{ payslips: PayslipRecord[] }>({
    queryKey: ["/api/payslips"],
  });

  const payslips = payslipsData?.payslips || [];

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold mb-2">Payslips</h2>
          <p className="text-sm text-muted-foreground">
            View your approved payslips
          </p>
        </div>
        <div className="grid gap-4">
          {[1, 2, 3].map((i) => (
            <Card key={i}>
              <CardHeader>
                <Skeleton className="h-6 w-48" />
              </CardHeader>
              <CardContent>
                <Skeleton className="h-24 w-full" />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-semibold mb-2" data-testid="text-page-title">
          Payslips
        </h2>
        <p className="text-sm text-muted-foreground">
          View your approved payslips based on attendance hours
        </p>
      </div>

      {payslips.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <DollarSign className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
            <h3 className="text-lg font-medium mb-2">No Payslips Available</h3>
            <p className="text-sm text-muted-foreground">
              Your approved payslips will appear here once they are generated by the admin.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {payslips.map((payslip) => {
            const actualHours = payslip.totalHours / 2; // Convert half-hours to hours
            const hourlyWageDollars = payslip.hourlyWage / 100; // Convert cents to dollars
            const totalPayDollars = payslip.totalPay / 100; // Convert cents to dollars

            return (
              <Card key={payslip.id} data-testid={`card-payslip-${payslip.id}`}>
                <CardHeader>
                  <CardTitle className="flex items-center justify-between">
                    <span className="flex items-center gap-2">
                      <DollarSign className="h-5 w-5" />
                      Payslip
                    </span>
                    <span className="text-sm font-normal text-muted-foreground" data-testid={`text-period-${payslip.id}`}>
                      {new Date(payslip.periodStart).toLocaleDateString('en-SG', { day: 'numeric', month: 'short', year: 'numeric' })} - {new Date(payslip.periodEnd).toLocaleDateString('en-SG', { day: 'numeric', month: 'short', year: 'numeric' })}
                    </span>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="text-muted-foreground">Period</p>
                      <p className="font-medium" data-testid={`text-payslip-period-${payslip.id}`}>
                        {new Date(payslip.periodStart).toLocaleDateString('en-SG', { day: 'numeric', month: 'short', year: 'numeric' })} to {new Date(payslip.periodEnd).toLocaleDateString('en-SG', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">Generated On</p>
                      <p className="font-medium" data-testid={`text-generated-date-${payslip.id}`}>
                        {new Date(payslip.createdAt!).toLocaleDateString('en-SG', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </p>
                    </div>
                  </div>

                  <Separator />

                  <div className="space-y-3">
                    <div className="flex justify-between items-center">
                      <div className="flex items-center gap-2">
                        <Clock className="h-4 w-4 text-muted-foreground" />
                        <span className="text-sm">Total Hours Worked</span>
                      </div>
                      <span className="font-mono font-medium" data-testid={`text-total-hours-${payslip.id}`}>
                        {actualHours.toFixed(1)} hours
                      </span>
                    </div>

                    <div className="flex justify-between items-center">
                      <span className="text-sm">Hourly Wage</span>
                      <span className="font-mono font-medium" data-testid={`text-hourly-wage-${payslip.id}`}>
                        ${hourlyWageDollars.toFixed(2)}/hour
                      </span>
                    </div>
                  </div>

                  <Separator />

                  <div className="bg-primary/10 p-4 rounded-lg">
                    <div className="flex justify-between items-center">
                      <span className="text-lg font-semibold">Total Pay</span>
                      <span className="text-2xl font-bold font-mono" data-testid={`text-total-pay-${payslip.id}`}>
                        ${totalPayDollars.toFixed(2)}
                      </span>
                    </div>
                    {payslip.approvedAt && (
                      <p className="text-xs text-muted-foreground mt-2">
                        Approved on {new Date(payslip.approvedAt).toLocaleDateString('en-SG', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
